# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trnkv7KjAmBijAYcKLJPlo7_O0qCfRGk
"""

import pandas as pd
df=pd.read_csv('car_Dekho_DA.csv',index_col=0)
df.info()
df.head(5)
df.isnull().sum()
df.drop_duplicates(inplace=True)
df.to_csv('car_Dekho_csv',index=True)

"""here we are facing issues of unnamed columns which is carbage columns so we should delete it"""

df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df.to_csv('car_Dekho_cleaned.csv', index=False)

df.duplicated().sum()

df.describe()

df['Fuel_Type'].value_counts()
df['Seller_Type'].value_counts()
df['Transmission'].value_counts()

"""visualization"""

import seaborn as sns
import matplotlib.pyplot as plt

"""1.histplot (Distribution of Numerical Data)
Selling Price Distribution
"""

sns.histplot(df['Selling_Price'],kde=True,bins=30,color='red')
plt.title('Selling Price Distribution')
plt.xlabel('Selling Price')
plt.ylabel('Frequency')
plt.show()

"""2. Count Plots for Categorical Data"""

sns.countplot(x='Fuel_Type',data=df,palette='Set2')
plt.title('Fuel Type Count')
plt.xlabel('Fuel Type')
plt.ylabel('count')
plt.show

sns.countplot(x='Seller_Type',data=df,palette='Set1')
plt.title('Seller Type Count')
plt.xlabel('Fuel Type')
plt.ylabel('count')
plt.show

""" 3.Box Plots (Categorical vs Numeric)"""

sns.boxplot(x='Fuel_Type',y='Selling_Price',data=df)
plt.title('Fuel Type vs Selling Price')
plt.xlabel('Fuel Type')
plt.ylabel('Selling Price')
plt.show()

"""4. Price vs Present Price / Year(Scatter Plot: Present Price vs Selling Price)"""

sns.scatterplot(x='Present_Price', y='Selling_Price', hue='Fuel_Type', data=df)
plt.title('Selling Price vs Present Price')
plt.xlabel('Presemnt Price')
plt.ylabel('selling Price')
plt.show()

"""5. Correlation Heatmap
Shows how strongly numerical features are related to each other.
"""

numeric_df = df.select_dtypes(include=['int64', 'float64'])
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap of Numeric Features")
plt.show()

print(df.dtypes)

""" Predictive Modeling Prep"""

#  encode categorical variables
df_model = pd.get_dummies(df, drop_first=True)

# Feature and target
X = df_model.drop('Selling_Price', axis=1)
y = df_model['Selling_Price']

# Train/test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#linear regression
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
#evaluation
from sklearn.metrics import r2_score
print("R2 Score:", r2_score(y_test, y_pred))

df.to_csv('car_Dekho_DA_cleaned.csv')